name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm run test:unit -- --coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-coverage
          path: coverage/
          retention-days: 7

  

  status-comment:
    name: Status Comment
    runs-on: ubuntu-latest
    needs: [lint, unit-test]
    if: always()
    permissions:
      pull-requests: write
    steps:
      - name: Download unit test coverage
        uses: actions/download-artifact@v5
        continue-on-error: true
        with:
          name: unit-test-coverage
          path: coverage/

      - name: Check job results
        id: check
        run: |
          if [[ "${{ needs.lint.result }}" == "success" && "${{ needs.unit-test.result }}" == "success" ]]; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "message=✅ All checks passed successfully!" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "message=❌ Some checks failed. Please review the results above." >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-status
          message: |
            ## Pull Request Status

            ${{ steps.check.outputs.message }}

            ### Job Results
            - **Lint**: ${{ needs.lint.result == 'success' && '✅ Passed' || '❌ Failed' }}
            - **Unit Tests**: ${{ needs.unit-test.result == 'success' && '✅ Passed' || '❌ Failed' }}

            ---
            *Updated at: ${{ github.event.pull_request.updated_at }}*
            *Commit: ${{ github.sha }}*

